/**
 * OpenNext Config Generator
 *
 * Generates open-next.config.ts based on caching strategy and configuration.
 *
 * @packageDocumentation
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import type { CloudflareConfig } from '../../../schemas/config.js';
import { logger } from '../../../utils/logger.js';

/**
 * Generates open-next.config.ts file
 *
 * @description
 * Creates the OpenNext.js Cloudflare configuration file based on the selected
 * caching strategy and other configuration options.
 *
 * @param config - Cloudflare configuration
 * @param projectRoot - Root directory of the project
 * @returns Promise that resolves when file is written
 *
 * @example
 * ```typescript
 * await generateOpenNextConfig(config, process.cwd());
 * ```
 */
export function generateOpenNextConfig(
  config: CloudflareConfig,
  projectRoot: string
): void {
  const filePath = join(projectRoot, 'open-next.config.ts');
  const content = generateOpenNextConfigContent(config);

  writeFileSync(filePath, content, 'utf-8');
  logger.success(`Generated open-next.config.ts`);
}

/**
 * Generates the content for open-next.config.ts
 *
 * @description
 * Creates the TypeScript configuration content based on caching strategy.
 *
 * @param config - Cloudflare configuration
 * @returns Configuration file content as string
 */
function generateOpenNextConfigContent(config: CloudflareConfig): string {
  const { cachingStrategy } = config;

  let importStatement = '';
  let cacheConfig = '';

  switch (cachingStrategy) {
    case 'static-assets':
      importStatement =
        'import staticAssetsIncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/static-assets-incremental-cache";';
      cacheConfig = 'incrementalCache: staticAssetsIncrementalCache,';
      break;

    case 'r2':
      importStatement =
        'import r2IncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-incremental-cache";';
      cacheConfig = 'incrementalCache: r2IncrementalCache,';
      break;

    case 'r2-do-queue':
      importStatement =
        'import r2DoQueueIncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-do-queue-incremental-cache";';
      cacheConfig = 'incrementalCache: r2DoQueueIncrementalCache,';
      break;

    case 'r2-do-queue-tag-cache':
      importStatement =
        'import r2DoQueueTagCacheIncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-do-queue-tag-cache-incremental-cache";';
      cacheConfig = 'incrementalCache: r2DoQueueTagCacheIncrementalCache,';
      break;
  }

  return `import { defineCloudflareConfig } from "@opennextjs/cloudflare";
${importStatement}

/**
 * OpenNext Cloudflare Configuration
 * 
 * Generated by opennextjs-cli
 * 
 * Caching Strategy: ${cachingStrategy}
 * Next.js Version: ${config.nextJsVersion}
 * 
 * See: https://opennext.js.org/cloudflare
 */
export default defineCloudflareConfig({
  ${cacheConfig}
  enableCacheInterception: true,
});
`;
}
